update faq with common ask questions
aws-quickstart/quickstart-aws-utility-meter-data-analytics-platform pull request #20
Opened 2021-03-03 15:42 UTC by SaschaJanssen

*Issue #, if available:*

*Description of changes:*
Update FAQ with commonly asked questions.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-03-03 20:16 UTC, sshvans requested changes
Please see my comments.

2021-03-03 20:16 UTC, sshvans commented on docs/partner_editable/faq_troubleshooting.adoc
> +*A.* AWS is an exceptionally customer obsessed company. 90% of what AWS builds is what AWS customers directly ask for, while the remaining 10% is focused on strategic interpretations of customer need
```suggestion
*A.* Utility customers have expressed a need to breakdown the data silos and bring greater value out of their data; in this case meter data. Customers asked for AWS best practices for storing meter data in a data lake, and then help to quickly get started running analytics and ML against that data to derive value for their own customers. This Quick Start (QS) directly answers these needs. Utilities can hydrate the AWS data lake in this QS with Data from their existing systems and continue to evolve this QS to meet their business needs. We expect our customers, solution providers and system integrators to take advantage of this QS, which allows utilities to start exploiting ML against their meter data in a matter of days.
```

2021-03-03 20:16 UTC, sshvans commented on docs/partner_editable/faq_troubleshooting.adoc
> +*A.* Some of our ISV and SI partners are attempting this. We are working with them to adopt our QS as a starting point. When it comes to On-prem, every utility has meter data and an MDM, and do some
```suggestion
*A.* Some of the AWS partners are working to adopt the Quick Start as a starting point and building on top of it. When it comes to on-premises, most utility has meter data and an MDM, and do some degree of analytics against the data. Very few do any form of ML against the data. Most want to do more, and do it in the cloud, to free themselves from the costs and constraint of on-premises analytics and ML.
```

2021-03-03 20:16 UTC, sshvans commented on docs/partner_editable/faq_troubleshooting.adoc
> +*A.* Timestream was not available at the event of the MDA. We have plans to look into Timestream in the future. Timestream is a good option for certain use cases, i.e. real time dashboards.
```suggestion
*A.* Timestream was not available at the time of the publication of this Quick Start. We are looking into updating it in future iterations. Timestream is a good option for certain use cases, i.e. real time dashboards.
```

2021-03-17 17:27 UTC, MarciaRieferJohnston commented on docs/partner_editable/faq_troubleshooting.adoc
> +*A.* We recommend that you launch the Quick Start templates from the links in this guide or from another S3 bucket. If you deploy the templates from a local copy on your computer or from a location o
Quick note—Here's the latest version of this answer as it has been edited in our current boilerplate: 

Launch the Quick Start templates from the links in this guide or from another S3 bucket. If you deploy the templates from a local copy on your computer or from a location other than an S3 bucket, you might encounter template-size limitations. For more information, see http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cloudformation-limits.html[AWS CloudFormation quotas^].

2021-03-17 18:13 UTC, annaone approved these changes

2021-03-17 18:13 UTC, merged